project_id = "dadaeduevxyvkhjmwlel"

[functions.cluster-assistant]
verify_jwt = false

[functions.agent-receive-metrics]
verify_jwt = false

[functions.agent-get-commands]
verify_jwt = false

[functions.agent-update-command]
verify_jwt = false

[functions.verify-docker-image]
verify_jwt = false

[functions.agent-retry-failed-commands]
verify_jwt = false

[functions.auto-analyze-clusters]
verify_jwt = false