apiVersion: v1
kind: Namespace
metadata:
  name: kodo
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kodo-agent
  namespace: kodo
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kodo-agent
rules:
- apiGroups: [""]
  resources: ["nodes", "pods", "events", "namespaces", "persistentvolumeclaims", "persistentvolumes", "secrets", "resourcequotas", "limitranges", "services", "configmaps", "endpoints"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["nodes/proxy", "nodes/stats"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["delete"]
- apiGroups: ["apps"]
  resources: ["deployments", "daemonsets", "replicasets", "statefulsets"]
  verbs: ["get", "list", "watch", "update", "patch"]
- apiGroups: ["metrics.k8s.io"]
  resources: ["nodes", "pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["roles", "rolebindings", "clusterroles", "clusterrolebindings"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["networking.k8s.io"]
  resources: ["networkpolicies", "ingresses", "ingressclasses"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kodo-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kodo-agent
subjects:
- kind: ServiceAccount
  name: kodo-agent
  namespace: kodo
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kodo-config
  namespace: kodo
data:
  API_ENDPOINT: "https://dadaeduevxyvkhjmwlel.supabase.co/functions/v1"
  COLLECT_INTERVAL: "15"
---
apiVersion: v1
kind: Secret
metadata:
  name: kodo-secret
  namespace: kodo
type: Opaque
stringData:
  API_KEY: "kp_5471324356aa4091aae5453794dad2f5"
  CLUSTER_ID: "4e630bb6-99f5-4787-b662-f8fe38dbc31f"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kodo-agent
  namespace: kodo
  labels:
    app: kodo-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kodo-agent
  template:
    metadata:
      labels:
        app: kodo-agent
    spec:
      serviceAccountName: kodo-agent
      containers:
      - name: agent
        image: ghcr.io/kubenetworks-group/kodo-agent:v0.0.47
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: kodo-config
        - secretRef:
            name: kodo-secret
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
            
