apiVersion: v1
kind: Namespace
metadata:
  name: kuberpulse
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kuberpulse-agent
  namespace: kuberpulse
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kuberpulse-agent
rules:
- apiGroups: [""]
  resources: ["nodes", "pods", "events", "namespaces"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["delete"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "update"]
- apiGroups: ["metrics.k8s.io"]
  resources: ["nodes", "pods"]
  verbs: ["get", "list", "watch"]


---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kuberpulse-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kuberpulse-agent
subjects:
- kind: ServiceAccount
  name: kuberpulse-agent
  namespace: kuberpulse
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kuberpulse-config
  namespace: kuberpulse
data:
  API_ENDPOINT: "https://dadaeduevxyvkhjmwlel.supabase.co/functions/v1"
  COLLECT_INTERVAL: "15"
---
apiVersion: v1
kind: Secret
metadata:
  name: kuberpulse-secret
  namespace: kuberpulse
type: Opaque
stringData:
  API_KEY: "eyJhbGciOiJSUzI1NiIsImtpZCI6IkZ0a1liRHdWczNZX3dxc0NHcF92Q1dMS1ZIZV95Q0JYVmRlM2JtQ2NSOEUifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjIl0sImV4cCI6MTc2MzQyOTk4OSwiaWF0IjoxNzYzNDI2Mzg5LCJpc3MiOiJodHRwczovL2t1YmVybmV0ZXMuZGVmYXVsdC5zdmMiLCJqdGkiOiI2M2VkMGEwZi03YWRmLTRmY2UtYWUxNy0yNWExNzM4NThjMmMiLCJrdWJlcm5ldGVzLmlvIjp7Im5hbWVzcGFjZSI6Imt1YmVycHVsc2UiLCJzZXJ2aWNlYWNjb3VudCI6eyJuYW1lIjoia3ViZXJwdWxzZS1hZ2VudCIsInVpZCI6IjI0NDA5MGEzLWNiZjItNDI4Yy04MDViLTEyMzYxODkyOWU2MyJ9fSwibmJmIjoxNzYzNDI2Mzg5LCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6a3ViZXJwdWxzZTprdWJlcnB1bHNlLWFnZW50In0.D5OxIb1ZzaEwFGWkwr47Owre0wIJX8ESKVeBxOWakFe2L50M8PIVjvxGLfuio13nHXC4TsAP5IG8Ld1RHgI3mIUqBXP3zuvOohU9-jcPpLJAGv3e5LkLTtTFRgzmykaOiLrL0rTYfjg8NmXASkRqeQxt32oU2srXcrDoTXetQ5jRn2pwXu7pEX54f7-Zuj9eOlsRb-GSdma3eeDm26gdIXmQZ0GyB4DifZINIPuUzqD_HpW2fPopnqKUHxmisv7kbgSR4SZaPCB8FI1zPWpY9exvNCQsKh9hVgGwm1XnL9Nh7HagPFSeuwcvYAIPjXyQNJfXLwpP722RDXWICpUVJg"
  CLUSTER_ID: "2ba92131-8573-4651-96e9-5ad888282a7b"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuberpulse-agent
  namespace: kuberpulse
  labels:
    app: kuberpulse-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kuberpulse-agent
  template:
    metadata:
      labels:
        app: kuberpulse-agent
    spec:
      serviceAccountName: kuberpulse-agent
      containers:
      - name: agent
        image: docker.io/denercavalcante/kuberpulse-agent:v0.0.1
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: kuberpulse-config
        - secretRef:
            name: kuberpulse-secret
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"